--- Data Cleaning ?
--(1.) Missing Values Check - shopping_trends Table
SELECT
	COUNT(*) FILTER (
		WHERE
			CUSTOMER_ID IS NULL
	) AS CUSTOMER_ID_NULL,
	COUNT(*) FILTER (
		WHERE
			AGE IS NULL
	) AS AGE_NULL,
	COUNT(*) FILTER (
		WHERE
			GENDER IS NULL
	) AS GENDER_NULL,
	COUNT(*) FILTER (
		WHERE
			ITEM_PURCHASED IS NULL
	) AS ITEM_PURCHASED_NULL,
	COUNT(*) FILTER (
		WHERE
			CATEGORY IS NULL
	) AS CATEGORY_NULL,
	COUNT(*) FILTER (
		WHERE
			PURCHASE_AMOUNT_USD IS NULL
	) AS PURCHASE_AMOUNT_USD_NULL,
	COUNT(*) FILTER (
		WHERE
			LOCATION IS NULL
	) AS LOCATION_NULL,
	COUNT(*) FILTER (
		WHERE
			SIZE IS NULL
	) AS SIZE_NULL,
	COUNT(*) FILTER (
		WHERE
			COLOR IS NULL
	) AS COLOR_NULL,
	COUNT(*) FILTER (
		WHERE
			SEASON IS NULL
	) AS SEASON_NULL,
	COUNT(*) FILTER (
		WHERE
			REVIEW_RATING IS NULL
	) AS REVIEW_RATING_NULL,
	COUNT(*) FILTER (
		WHERE
			SUBSCRIPTION_STATUS IS NULL
	) AS SUBSCRIPTION_STATUS_NULL,
	COUNT(*) FILTER (
		WHERE
			PAYMENT_METHOD IS NULL
	) AS PAYMENT_METHOD_NULL,
	COUNT(*) FILTER (
		WHERE
			SHIPPING_TYPE IS NULL
	) AS SHIPPING_TYPE_NULL,
	COUNT(*) FILTER (
		WHERE
			DISCOUNT_APPLIED IS NULL
	) AS DISCOUNT_APPLIED_NULL,
	COUNT(*) FILTER (
		WHERE
			PROMO_CODE_USED IS NULL
	) AS PROMO_CODE_USED_NULL,
	COUNT(*) FILTER (
		WHERE
			PREVIOUS_PURCHASES IS NULL
	) AS PREVIOUS_PURCHASES_NULL,
	COUNT(*) FILTER (
		WHERE
			PREFERRED_PAYMENT_METHOD IS NULL
	) AS PREFERRED_PAYMENT_METHOD_NULL,
	COUNT(*) FILTER (
		WHERE
			FREQUENCY_OF_PURCHASES IS NULL
	) AS FREQUENCY_OF_PURCHASES_NULL
FROM
	SHOPPING_TRENDS;

--  Misisng Value Check - shopping_trends_updated Table
SELECT
	COUNT(*) FILTER (
		WHERE
			CUSTOMER_ID IS NULL
	) AS CUST_ID_NULL,
	COUNT(*) FILTER (
		WHERE
			AGE IS NULL
	) AS AGE_NULL,
	COUNT(*) FILTER (
		WHERE
			GENDER IS NULL
	) AS GENDER_NULL,
	COUNT(*) FILTER (
		WHERE
			ITEM_PURCHASED IS NULL
	) AS ITEM_PURCHASED_NULL,
	COUNT(*) FILTER (
		WHERE
			PURCHASE_AMOUNT_USD IS NULL
	) AS PURCHASE_AMOUNT_USD_NULL,
	COUNT(*) FILTER (
		WHERE
			LOCATION IS NULL
	) AS LOCATION_NULL,
	COUNT(*) FILTER (
		WHERE
			SIZE IS NULL
	) AS SIZE_NULL,
	COUNT(*) FILTER (
		WHERE
			LOCATION IS NULL
	) AS LOCATION_NULL,
	COUNT(*) FILTER (
		WHERE
			COLOR IS NULL
	) AS COLOR_NULL,
	COUNT(*) FILTER (
		WHERE
			SEASON IS NULL
	) AS SEASON_NULL,
	COUNT(*) FILTER (
		WHERE
			REVIEW_RATING IS NULL
	) AS REVIEW_RATING_NULL,
	COUNT(*) FILTER (
		WHERE
			SUBSCRIPTION_STATUS IS NULL
	) AS SUBSCRIPTION_STATUS_NULL,
	COUNT(*) FILTER (
		WHERE
			SHIPPING_TYPE IS NULL
	) AS SHIPPING_TYPE_NULL,
	COUNT(*) FILTER (
		WHERE
			DISCOUNT_APPLIED IS NULL
	) AS DISCOUNT_APPLIED_NULL,
	COUNT(*) FILTER (
		WHERE
			PROMO_CODE_USED IS NULL
	) AS PROMO_CODE_USED_NULL,
	COUNT(*) FILTER (
		WHERE
			PREVIOUS_PURCHASES IS NULL
	) AS PREVIOUS_PURCHASES_NULL,
	COUNT(*) FILTER (
		WHERE
			PAYMENT_METHOD IS NULL
	) AS PAYMENT_METHOD_NULL,
	COUNT(*) FILTER (
		WHERE
			FREQUENCY_OF_PURCHASES IS NULL
	) AS FREQUENCY_OF_PURCHASES_NULL
FROM
	SHOPPING_TRENDS_UPDATED;

-- (2.) Duplicated Find - 
-- duplicat Find - shopping_trends Table
SELECT
	CUSTOMER_ID,
	AGE,
	GENDER,
	ITEM_PURCHASED,
	CATEGORY,
	PURCHASE_AMOUNT_USD,
	COUNT(*)
FROM
	SHOPPING_TRENDS
GROUP BY
	CUSTOMER_ID,
	AGE,
	GENDER,
	ITEM_PURCHASED,
	CATEGORY,
	PURCHASE_AMOUNT_USD
HAVING
	COUNT(*) > 1;

-- duplicat Find - shopping_trends_updated Table
SELECT
	CUSTOMER_ID,
	AGE,
	GENDER,
	ITEM_PURCHASED,
	CATEGORY,
	PURCHASE_AMOUNT_USD,
	COUNT(*)
FROM
	SHOPPING_TRENDS_UPDATED
GROUP BY
	CUSTOMER_ID,
	AGE,
	GENDER,
	ITEM_PURCHASED,
	CATEGORY,
	PURCHASE_AMOUNT_USD
HAVING
	COUNT(*) > 1;

--(3.) Invalid Values check 
SELECT
	PURCHASE_AMOUNT_USD,
	REVIEW_RATING,
	PREVIOUS_PURCHASES,
	AGE
FROM
	SHOPPING_TRENDS
WHERE
	PURCHASE_AMOUNT_USD < 0
	OR REVIEW_RATING < 0
	OR PREVIOUS_PURCHASES < 0
	OR AGE < 0;

-- (4.) Invalid Entry check
SELECT
	SUBSCRIPTION_STATUS,
	PROMO_CODE_USED,
	PAYMENT_METHOD
FROM
	SHOPPING_TRENDS
WHERE
	SUBSCRIPTION_STATUS NOT IN ('Yes', 'No')
	OR PROMO_CODE_USED NOT IN ('Yes', 'No')
	OR PAYMENT_METHOD NOT IN (
		'PayPal',
		'Debit Card',
		'Credit Card',
		'Venmo',
		'Cash',
		'Bank Transfer'
	);

-- (5.) Gender standardization
SELECT DISTINCT
	GENDER
FROM
	SHOPPING_TRENDS;

-- (6.) standardization & Trim Extra spaces 
-- (1) shopping_trends_updated Table
UPDATE SHOPPING_TRENDS_UPDATED
SET
	GENDER = INITCAP(TRIM(GENDER)),
	ITEM_PURCHASED = INITCAP(TRIM(ITEM_PURCHASED)),
	CATEGORY = INITCAP(TRIM(CATEGORY)),
	LOCATION = INITCAP(TRIM(LOCATION)),
	SIZE = INITCAP(TRIM(SIZE)),
	COLOR = INITCAP(TRIM(COLOR)),
	SEASON = INITCAP(TRIM(SEASON)),
	SUBSCRIPTION_STATUS = INITCAP(TRIM(SUBSCRIPTION_STATUS)),
	SHIPPING_TYPE = INITCAP(TRIM(SHIPPING_TYPE)),
	DISCOUNT_APPLIED = INITCAP(TRIM(DISCOUNT_APPLIED)),
	PROMO_CODE_USED = INITCAP(TRIM(PROMO_CODE_USED)),
	PAYMENT_METHOD = INITCAP(TRIM(PAYMENT_METHOD)),
	FREQUENCY_OF_PURCHASES = INITCAP(TRIM(FREQUENCY_OF_PURCHASES));

--(2) shopping_trends Table
UPDATE SHOPPING_TRENDS
SET
	GENDER = INITCAP(TRIM(GENDER)),
	ITEM_PURCHASED = INITCAP(TRIM(ITEM_PURCHASED)),
	CATEGORY = INITCAP(TRIM(CATEGORY)),
	LOCATION = INITCAP(TRIM(LOCATION)),
	SIZE = INITCAP(TRIM(SIZE)),
	COLOR = INITCAP(TRIM(COLOR)),
	SEASON = INITCAP(TRIM(SEASON)),
	SUBSCRIPTION_STATUS = INITCAP(TRIM(SUBSCRIPTION_STATUS)),
	PAYMENT_METHOD = INITCAP(TRIM(PAYMENT_METHOD)),
	SHIPPING_TYPE = INITCAP(TRIM(SHIPPING_TYPE)),
	DISCOUNT_APPLIED = INITCAP(TRIM(DISCOUNT_APPLIED)),
	PROMO_CODE_USED = INITCAP(TRIM(PROMO_CODE_USED)),
	PREFERRED_PAYMENT_METHOD = INITCAP(TRIM(PREFERRED_PAYMENT_METHOD)),
	FREQUENCY_OF_PURCHASES = INITCAP(TRIM(FREQUENCY_OF_PURCHASES));