-- 🛒 Customer & Sales Analysis 
-- 1.	Which product categories generate the highest total revenue? 
SELECT
	CATEGORY,
	ROUND(SUM(PURCHASE_AMOUNT_USD), 2) AS TOTAL_REVENUE
FROM
	SHOPPING_TRENDS
GROUP BY
	CATEGORY
ORDER BY
	TOTAL_REVENUE DESC
LIMIT
	1;

-- 2.	Which products are the top 10 best-selling items by purchase amount?
SELECT
	ITEM_PURCHASED,
	ROUND(SUM(PURCHASE_AMOUNT_USD), 2) AS TOTAL_REVENUE
FROM
	SHOPPING_TRENDS
GROUP BY
	ITEM_PURCHASED
ORDER BY
	TOTAL_REVENUE DESC
LIMIT
	10;

-- 3.	Which locations generate the highest revenue and number of purchases? 
SELECT
	LOCATION,
	ROUND(SUM(PURCHASE_AMOUNT_USD), 2) AS TOTAL_REVENUE,
	COUNT(*) AS TOTAL_PURCHASE
FROM
	SHOPPING_TRENDS
GROUP BY
	LOCATION
ORDER BY
	TOTAL_REVENUE DESC
LIMIT
	1;

-- 4.	Which age groups contribute the most revenue? 
SELECT
	AGE,
	ROUND(SUM(PURCHASE_AMOUNT_USD), 2) AS TOTAL_REVENUE
FROM
	SHOPPING_TRENDS
GROUP BY
	AGE
ORDER BY
	TOTAL_REVENUE DESC
LIMIT
	1;

-- 5.	What is the average purchase amount by gender? 
SELECT
	GENDER,
	ROUND(AVG(PURCHASE_AMOUNT_USD), 2) AS AVG_AMOUNT
FROM
	SHOPPING_TRENDS
GROUP BY
	GENDER
ORDER BY
	AVG_AMOUNT DESC;

-- 💳 Payment & Customer Behavior 
-- 6.	Which payment method is most preferred by customers? 
SELECT
	PREFERRED_PAYMENT_METHOD,
	PAYMENT_METHOD,
	COUNT(CUSTOMER_ID) AS TOTAL_PURCHASE
FROM
	SHOPPING_TRENDS
GROUP BY
	PREFERRED_PAYMENT_METHOD,
	PAYMENT_METHOD
ORDER BY
	TOTAL_PURCHASE DESC
LIMIT
	1;

-- 7.	Are customers using their preferred payment method when making purchases? 
SELECT
	PREFERRED_PAYMENT_METHOD,
	PAYMENT_METHOD,
	COUNT(CUSTOMER_ID) TOTAL__PURCHASE,
	ROUND(
		100.0 * COUNT(CUSTOMER_ID) / SUM(COUNT(CUSTOMER_ID)) OVER (
			PARTITION BY
				PREFERRED_PAYMENT_METHOD
		),
		2
	) AS PCT_OF_PURCHASE
FROM
	SHOPPING_TRENDS
GROUP BY
	PREFERRED_PAYMENT_METHOD,
	PAYMENT_METHOD
ORDER BY
	TOTAL__PURCHASE DESC;

-- 8.	Which customer segments have the highest number of previous purchases? 
SELECT
	CASE
		WHEN AGE < 25 THEN 'Under 25'
		WHEN AGE BETWEEN 25 AND 40  THEN '25-40'
		WHEN AGE BETWEEN 41 AND 60  THEN '41-60'
		ELSE '60+'
	END AS AGE_SEGMENT,
	COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMER,
	ROUND(SUM(PREVIOUS_PURCHASES), 2) AS TOTAL_PREVIOUS_PURCHASES,
	ROUND(AVG(PREVIOUS_PURCHASES), 2) AS AVG_PREVIOUS_PURCHASES
FROM
	SHOPPING_TRENDS
GROUP BY
	CASE
		WHEN AGE < 25 THEN 'Under 25'
		WHEN AGE BETWEEN 25 AND 40  THEN '25-40'
		WHEN AGE BETWEEN 41 AND 60  THEN '41-60'
		ELSE '60+'
	END
ORDER BY
	TOTAL_PREVIOUS_PURCHASES DESC;

-- 9. 	Do customers with subscriptions spend more than non-subscribers? 
SELECT
	SUBSCRIPTION_STATUS,
	COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMER,
	ROUND(SUM(PURCHASE_AMOUNT_USD), 2) AS TOTAL_PURCHASE_AMOUNT,
	ROUND(AVG(PURCHASE_AMOUNT_USD), 2) AS AVG_PURCHASE_AMOUNT
FROM
	SHOPPING_TRENDS
GROUP BY
	SUBSCRIPTION_STATUS;

-- 🎯 Marketing & Discount Analysis 
-- 10. DOES APPLYING A DISCOUNT INCREASE THE AVERAGE PURCHASE AMOUNT ?
SELECT
	DISCOUNT_APPLIED,
	COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMER,
	ROUND(SUM(PURCHASE_AMOUNT_USD), 2) AS TOTAL_AMOUNT,
	ROUND(AVG(PURCHASE_AMOUNT_USD), 2) AS AVG_PURCHASE_AMOUNT
FROM
	SHOPPING_TRENDS
GROUP BY
	DISCOUNT_APPLIED;

-- 11.	What percentage of customers use promo codes? 
SELECT 
    ROUND(
        COUNT(CASE WHEN promo_code_used IN ('Yes', 'YES', '1') THEN 1 END) * 100.0 / COUNT(*), 
        2
    ) AS promo_code_usage_percentage
FROM shopping_trends;

-- 12.	Which categories have the highest promo-code usage? 
SELECT DISTINCT
	CATEGORY,
	PROMO_CODE_USED,
	SUM(PURCHASE_AMOUNT_USD) AS TOTAL
FROM
	SHOPPING_TRENDS
GROUP BY
	CATEGORY,
	PROMO_CODE_USED
ORDER BY
	TOTAL DESC
LIMIT
	1;

-- 🚚 Operations & Customer Experience 
-- 13.	Which shipping type is most commonly selected by customers? 
SELECT
	SHIPPING_TYPE,
	COUNT(CUSTOMER_ID) AS HIGHEST_SELECT_CUSTOMER
FROM
	SHOPPING_TRENDS
GROUP BY
	SHIPPING_TYPE
ORDER BY
	HIGHEST_SELECT_CUSTOMER DESC
LIMIT
	1;

-- 14.	Which categories receive the highest average review ratings? 
SELECT
	CATEGORY,
	ROUND(AVG(REVIEW_RATING), 2) AS AVG_RATING
FROM
	SHOPPING_TRENDS
GROUP BY
	CATEGORY
ORDER BY
	AVG_RATING DESC
LIMIT
	1;

-- 15.	Which combination of category, season, and location generates the highest sales? 
SELECT DISTINCT
	CATEGORY,
	SEASON,
	LOCATION,
	ROUND(SUM(PURCHASE_AMOUNT_USD), 2) AS HIGHEST_REVENUE
FROM
	SHOPPING_TRENDS
GROUP BY
	CATEGORY,
	SEASON,
	LOCATION
ORDER BY
	HIGHEST_REVENUE DESC
LIMIT
	1;





SELECT
	*
FROM
	SHOPPING_TRENDS
LIMIT
	5;

SELECT
	*
FROM
	SHOPPING_TRENDS_UPDATED
LIMIT
	5;